### ISSUE TITLE
fence_vmware_soap does not move in RHEL6.7.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/fence-agents#58]
Hi,

Python of RHEL6.7 varies in a parameter of logging.StreamHandler for 2.6.6.

[root@rh67-01 rpm]# fence_vmware_soap -o list -a "xxx.xxx.xx.xx" -l "xxxx" -p "xxx" -z --ssl-insecure
Traceback (most recent call last):
  File "/usr/sbin/fence_vmware_soap", line 257, in <module>
    main()
  File "/usr/sbin/fence_vmware_soap", line 223, in main
    options_global = check_input(device_opt, process_input(device_opt))
  File "/usr/share/fence/fencing.py", line 633, in check_input
    logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stderr))
TypeError: __init__() got an unexpected keyword argument 'stream'

I think that the following correction is necessary.

`/fence/agents/lib/fencing.py
(snip)
    632         ## add logging to stderr
    633         if sys.version_info >= (2, 7, 0):
    634                 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stderr))
    635         else:
    636                 logging.getLogger().addHandler(logging.StreamHandler(strm=sys.stderr))
(snip)

Best Regards,
Hideo Yamauchi.

**Comment by lge** [comment]
On Mon, Feb 22, 2016 at 09:55:55PM -0800, Hideo Yamauchi wrote:
> Hi,
> 
> Python of RHEL6.7 varies in a parameter of logging.StreamHandler for 2.6.6.
> 
> [root@rh67-01 rpm]# fence_vmware_soap -o list -a "xxx.xxx.xx.xx" -l "xxxx" -p "xxx" -z --ssl-insecure
> Traceback (most recent call last):
>   File "/usr/sbin/fence_vmware_soap", line 257, in <module>
>     main()
>   File "/usr/sbin/fence_vmware_soap", line 223, in main
>     options_global = check_input(device_opt, process_input(device_opt))
>   File "/usr/share/fence/fencing.py", line 633, in check_input
>     logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stderr))
> TypeError: __init__() got an unexpected keyword argument 'stream'
> 
> 
> I think that the following correction is necessary.
> 
> `/fence/agents/lib/fencing.py
> (snip)
>     632         ## add logging to stderr
>     633         if sys.version_info >= (2, 7, 0):
>     634                 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stderr))
>     635         else:
>     636                 logging.getLogger().addHandler(logging.StreamHandler(strm=sys.stderr))
> (snip)

Just leave off the kvarg style "name=",
arg style positional is just fine:

diff --git a/fence/agents/lib/fencing.py.py b/fence/agents/lib/fencing.py.py
--- a/fence/agents/lib/fencing.py.py
+++ b/fence/agents/lib/fencing.py.py
@@ -647,7 +647,7 @@
 	## add logging to syslog
 	logging.getLogger().addHandler(SyslogLibHandler())
 	## add logging to stderr
-	logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stderr))
+	logging.getLogger().addHandler(logging.StreamHandler(sys.stderr))
 
 	(acceptable_actions, _) = _get_available_actions(device_opt)

**Comment by HideoYamauchi** [comment]
Hi Lars,

Thank you for showing a right modification.
Please reflect the correction that you showed.

Best Regards,
Hideo Yamauchi.

**Comment by marxsk** [comment]
Sorry, this will not be fixed. There are also other issues that may not work in python2.6 and olders. Our priority for upstream is currently python2.7 and we are preparing migration to python3. 

For python2.6 feel free to use RHEL6 version where this bug is fixed.

**Comment by HideoYamauchi** [comment]
Okay!

We understood the policy as specifications.

Many thanks,
Hideo Yamauchi.
