### PR TITLE
fence_azure_arm: use azure-identity instead of msrestazure, which has been deprecated

### PR DESCRIPTION
**Pull request by HappyTobi**
Hi all,

this is a implementation to use `azure.identity` instead of `msrestazure`.
`msrestazure` is still there and will be used when `azure.identity` is not available.

Br

### CODE REVIEW

File: lib/azure_fence.py.py [hunk 1]
```diff
@@ -270,10 +270,49 @@ def get_azure_config(options):
...
+
 def get_azure_cloud_environment(config):
-    cloud_environment = None
-    if config.Cloud:
+    if (config.Cloud is None):
+        config.Cloud = "public"
+
+    try:
+        from azure.mgmt.core import tools
+        import azure.core.settings as settings
```
Comment (oalbrigt) [inline lib/azure_fence.py.py:297]: This doesnt work with azure-core 1.24.2, which is the newest version we can use on RHEL8.

Comment (HappyTobi) [reply lib/azure_fence.py.py:297]: Thx, I will take a look

Comment (HappyTobi) [reply lib/azure_fence.py.py:297]: Yes it's not available in that version :-(.
azure-core 1.24.2 was released on June 30 2022.
The function that I use was introduced in 1.31.0 (September 12 2024)

In the older releases is now azure endpoint handling implemented.

Can you please tell me the version for azure.mgmt.core that is available for Rel8?

**Comment by HappyTobi** [comment]
@oalbrigt 
Hi,
I tested the code again with the dependency versions that I found in the rpm package description.

Now it should run with old and new versions.
The background of the topic is that, that some distributions will remove the deprecated "msrestazure" dependency.

**Comment by oalbrigt** [comment]
@HappyTobi We also need to remove msrestazure on RHEL8, as we've seen issues using it in some cases. The fallback (except) code is just important to have where they need the updated code, but the distro cant upgrade the libs.

**Comment by HappyTobi** [comment]
> @HappyTobi We also need to remove msrestazure on RHEL8, as we've seen issues using it in some cases. The fallback (except) code is just important to have where they need the updated code, but the distro cant upgrade the libs.

For sure thats why I implemented a fallback for the versions you are using on RHEL8 currently.

**Comment by oalbrigt** [comment]
These are the upgraded versions. We cant upgrade past what works with Python 3.6.8 (being used on RHEL8) in this case.

And msrestazure has started causing issues, so we cant rely on that either.

I guess we'll have to find a way to backport azure.core.settings to work with that Python version.

**Comment by oalbrigt** [comment]
@HappyTobi Let's add the handling to the local file in that case.

**Comment by HappyTobi** [comment]
@oalbrigt 
I added it to the local file.

File: lib/azure_fence.py.py [hunk 2]
```diff
@@ -350,39 +412,43 @@ def get_azure_compute_client(config):
     cloud_environment = get_azure_cloud_environment(config)
     credentials = get_azure_credentials(config)
 
-    if cloud_environment:
-        if (config.Cloud.lower() == "stack") and not config.MetadataEndpoint:
-                fail_usage("metadata-endpoint not specified")
+    from azure.mgmt.compute import __version__
```
Comment (oalbrigt) [inline lib/azure_fence.py.py:415]: __version__ isnt available in azure_mgmt_compute-27.2.0:
```
Traceback (most recent call last):
  File "./fence_azure_arm", line 272, in <module>
    main()
  File "./fence_azure_arm", line 250, in main
    compute_client = azure_fence.get_azure_compute_client(config)
  File "/usr/share/fence/azure_fence.py", line 415, in get_azure_compute_client
    from azure.mgmt.compute import __version__
ImportError: cannot import name '__version__'
```

Comment (HappyTobi) [reply lib/azure_fence.py.py:415]: Mhh ok than I tested it with the wrong version.
Do you have a list with the dependency versions that you are using when you run the fence_agent on RHEL8?

Comment (oalbrigt) [reply lib/azure_fence.py.py:415]: azure-common-1.1.28
azure-core-1.24.2
azure-mgmt-compute-27.2.0
azure-mgmt-core-1.3.2
azure-mgmt-network-20.0.0
azure-identity-1.10.0
msrest-0.7.1
msal-1.27.0
msal-extensions-1.0.0

**Comment by oalbrigt** [comment]
It's now working with my upgraded libraries on RHEL8, so I just need to do some additional testing to ensure it works in all scenarioes.

**Comment by HappyTobi** [comment]
> Just a couple of issues left. We will upgrade the libs, but it's important to have the fallback working as well for cases other distros or versions.
> 
> RHEL9 without upgraded libs:
> 
> ```
> $ fence_azure_arm ... -o list
> Traceback (most recent call last):
>   File "/usr/sbin/fence_azure_arm", line 276, in <module>
>     main()
>   File "/usr/sbin/fence_azure_arm", line 272, in main
>     result = fence_action([compute_client, network_client], options, set_power_status, get_power_status, get_nodes_list)
>   File "/usr/share/fence/fencing.py", line 976, in fence_action
>     outlets = get_outlet_list(connection, options)
>   File "/usr/sbin/fence_azure_arm", line 24, in get_nodes_list
>     vms = compute_client.virtual_machines.list(rgName)
>   File "/usr/lib/fence-agents/support/azure/azure/mgmt/compute/_compute_management_client.py", line 1546, in virtual_machines
>     raise ValueError("API version {} does not have operation group 'virtual_machines'".format(api_version))
> ValueError: API version 2021-11-01 does not have operation group 'virtual_machines'
> ```
> 
> RHEL8 without upgraded libs:
> 
> ```
> $ fence_azure_arm ... -o list
> Traceback (most recent call last):
>   File "./fence_azure_arm", line 272, in <module>
>     main()
>   File "./fence_azure_arm", line 268, in main
>     result = fence_action([compute_client, network_client], options, set_power_status, get_power_status, get_nodes_list)
>   File "/usr/share/fence/fencing.py", line 941, in fence_action
>     outlets = get_outlet_list(connection, options)
>   File "./fence_azure_arm", line 20, in get_nodes_list
>     vms = compute_client.virtual_machines.list(rgName)
>   File "/usr/lib/python3.6/site-packages/azure/mgmt/compute/compute_management_client.py", line 799, in virtual_machines
>     raise NotImplementedError("APIVersion {} is not available".format(api_version))
> NotImplementedError: APIVersion 2021-11-01 is not available
> ```

Is it possible that you share the versions? 
Than it's easier to test the different versions.

Thank you

**Comment by oalbrigt** [comment]
RHEL9:
adal-1.2.7
azure_common-1.1.27
azure_core-1.15.0
azure_identity-1.10.0
azure_mgmt_compute-21.0.0
azure_mgmt_core-1.2.2
azure_mgmt_network-19.0.0
msal_extensions-1.0.0
msrest-0.6.21
msrestazure-0.6.4

RHEL8 (condensed as azure-sdk contains lots of libs):
azure_common-1.1.19
azure_mgmt_compute-5.0.0
adal-1.2.0
msrest-0.6.2

**Comment by oalbrigt** [comment]
It's working fine without upgraded libs on RHEL8/RHEL9 now, but on RHEL8 with upgraded libs (listed above) I get the following error now:
```
# fence_azure_arm ... -o off
Traceback (most recent call last):
  File "/usr/sbin/fence_azure_arm", line 260, in <module>
    main()
  File "/usr/sbin/fence_azure_arm", line 256, in main
    result = fence_action([compute_client, network_client], options, set_power_status, get_power_status, get_nodes_list)
  File "/usr/share/fence/fencing.py", line 986, in fence_action
    if set_multi_power_fn(connection, options, set_power_fn, get_power_fn, sync_set_power_fn):
  File "/usr/share/fence/fencing.py", line 889, in set_multi_power_fn
    return async_set_multi_power_fn(connection, options, set_power_fn, get_power_fn, retry_attempts)
  File "/usr/share/fence/fencing.py", line 848, in async_set_multi_power_fn
    set_power_fn(connection, options)
  File "/usr/sbin/fence_azure_arm", line 120, in set_power_status
    compute_client.virtual_machines.power_off(rgName, vmName, skip_shutdown=True)
AttributeError: 'VirtualMachinesOperations' object has no attribute 'power_off'
```

**Comment by HappyTobi** [comment]
@oalbrigt I tested the changes with a larger set of different packages.
I also updated / extend my tests to create more clients to test the backwards compatibility

**Comment by oalbrigt** [comment]
Thanks. I will double check and get back to you.

**Comment by oalbrigt** [comment]
Everything is working fine now, so I guess I made a mistake when testing the other day 😄

**Comment by HappyTobi** [comment]
No I changed some things so I think you findings are fine.
I will also push my tests into my dev-pacemaker project for the next time we have to change something

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
Great. Nice to hear you have a way to try to avoid these kinds of issues in the future.

**Comment by HappyTobi** [comment]
@oalbrigt 
I will take a look tomorrow

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
No worries.
